[project]
name = "job-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.5",
    "pydantic-ai>=1.47.0",
    "pydantic-xml>=2.18.0",
]

[dependency-groups]
dev = [
    "docling>=2.94.0",
    "ipykernel>=7.2.0",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
