"""create user tables

Revision ID: 13ea009511a5
Revises: 
Create Date: 2026-07-12 17:40:17.803944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ea009511a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('CV_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_hash', sa.String(length=64), nullable=False),
    sa.Column('cv_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cv_hash', name='uq_user_cv_hash')
    )
    op.create_index(op.f('ix_CV_table_cv_hash'), 'CV_table', ['cv_hash'], unique=False)
    op.create_table('JD_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jd_hash', sa.String(length=64), nullable=False),
    sa.Column('jd_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jd_hash', name='uq_user_jd_hash')
    )
    op.create_index(op.f('ix_JD_table_jd_hash'), 'JD_table', ['jd_hash'], unique=False)
    op.create_table('Matched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matched_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['CV_table.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['JD_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id', 'jd_id', name='uq_cv_jd_match')
    )
    op.create_index(op.f('ix_Matched_score'), 'Matched', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Matched_score'), table_name='Matched')
    op.drop_table('Matched')
    op.drop_index(op.f('ix_JD_table_jd_hash'), table_name='JD_table')
    op.drop_table('JD_table')
    op.drop_index(op.f('ix_CV_table_cv_hash'), table_name='CV_table')
    op.drop_table('CV_table')
    op.drop_table('User_table')
    # ### end Alembic commands ###
